services:

  portal:
    image: leticiavitodeoliveira99/viaserra-portal:1.0-26174738   
    ports:
      - "8038:80"              
    restart: unless-stopped

  manutencao:
    build: ./manutencao       
    ports:
      - "7038:80"              
    restart: unless-stopped